layout_spectrum: 0.2659574
typography_spectrum: 0.4864611
color:
  lightness: 0.6659575
  brandStrength: 0.1273072
  saturation: 0.5574641
  rhythmicContrast: 0.4644218
  brandColors:
    - '#FFFFFF'
    - '#6E6860'
    - '#A3C9FB'
    - '#0D1014'
    - '#8D8769'
name: 'Little Car Landscape, LLC'
